version: "3"
services:
  main:
    image: panshiqu/deploy:v0.0.001
    deploy:
      replicas: 3
    ports:
      - "9090:9090"
    volumes:
      - "/root/docker/log:/app/log"
    environment:
      - TASKSLOT={{.Task.Slot}}
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]